#network
name: VGG # L0WideResNet
depth: 16
width: 0


#hyper parameters
epochs: 20
lr: 0.1
weight_decay: 0.0005
multi_gpu: True
lamba: 0.001
beta_ema: 0.99
droprate_init: 0.3
resume: False


#dataset
dataset: c100
batch_size: 128
N: 50000


#sparse constraint
iscloss: True
a: 100
lambdda: 1

#train
isadvtraining: True

#test
test_mode: PGD-10 #'base,PGD-10,PGD-20,AA,SA,FGSM'

#prune
isprune: True
isfinetune: False
sparsity: 0.01