
#network
name: L0WideResNet # L0WideResNet,VGG,VGG_BN
depth: 28
width: 10


#hyper parameters
epochs: 200
lr: 0.1
weight_decay: 0.0005
multi_gpu: True
lamba: 0.001
beta_ema: 0.99
droprate_init: 0.3
resume: False


#dataset
dataset: c10 #imagenet_1k  #c10,c100 ,imagenet_1k,tinyimagenet
batch_size: 128
N: 50000 #1281167
data_path: ../data #../../../dataset/ILSVRC2012_w  #cifar10_path:../data
seed: 1


#sparse constraint
iscloss: True
a: 100
lambdda: 1

#train
isadvtraining: True
save_path: ceshi #L0WideResNet
amp: False

#test
test_method: PGD_10 #'base,PGD_10,PGD_20,AA,SA,FGSM'

#prune
isprune: True
checkpoint_path:
freeze_bn: False
isfinetune: False
sparsity: 0.1 #leave